name: Tasks - Update specs

on:
  workflow_dispatch:
  push:
    branches:
      - add-workflow-update-specs

concurrency:
  group: update-specs
  cancel-in-progress: true

defaults:
  run:
    working-directory: packages/tasks

jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: true

      # Generate specs
      - run: pnpm run inference-tgi-import
      - run: pnpm run inference-tei-import
      - run: pnpm run inference-codegen

      # Check changes
      - run: git status

      # Create or update Pull Request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update tasks specs (automated commit)
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          branch: update-tasks-specs-automated-pr
          delete-branch: true
          title: "[Bot] Update tasks specs"
          body: |
            Tasks specs updated by running:
            ```sh
            pnpm run inference-tgi-import
            pnpm run inference-tei-import
            pnpm run inference-codegen
            ```

            This PR was automatically created by the [Tasks - Update specs workflow](https://github.com/huggingface/huggingface.js/blob/main/.github/update-specs.yml).
          labels: |
            tasks
            specs
          reviewers: |
            Wauplin
            hanouticelina
